version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
